<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/lib/security.php';
zurie_security_protect_sensitive_page();
require_once dirname(__DIR__) . '/lib/vault.php';
require_once dirname(__DIR__) . '/lib/server_metrics.php';
vault_start_session();

$error = '';
$message = '';
$newToken = '';
$newDevice = null;
$devices = sm_load_devices();

try {
    $pdo = sm_pdo();
    sm_ensure_schema($pdo);
} catch (Throwable $e) {
    $error = 'Database Server Metrics belum tersedia. Import sql/server_metrics.sql atau semak konfigurasi DB.';
}

if ($_SERVER['REQUEST_METHOD'] === 'POST' && $error === '') {
    try {
        if (!vault_is_unlocked()) throw new RuntimeException('Credential Vault mesti dibuka dahulu.');
        if (!vault_verify_csrf($_POST['csrf'] ?? null)) throw new RuntimeException('Token keselamatan tidak sah. Refresh halaman.');
        $action = (string)($_POST['action'] ?? '');
        $deviceId = trim((string)($_POST['device_id'] ?? ''));
        if (!isset($devices[$deviceId])) throw new RuntimeException('Server tidak sah.');

        if ($action === 'generate') {
            $newToken = bin2hex(random_bytes(32));
            $hash = hash('sha256', $newToken);
            $stmt = $pdo->prepare('INSERT INTO server_metric_agents (device_id, token_hash, enabled, note) VALUES (?, ?, 1, ?) ON DUPLICATE KEY UPDATE token_hash=VALUES(token_hash), enabled=1, note=VALUES(note), updated_at=CURRENT_TIMESTAMP');
            $stmt->execute([$deviceId, $hash, 'Generated by ZURIE']);
            $newDevice = $devices[$deviceId];
            $message = 'Token baharu dijana. Salin sekarang—token asal tidak disimpan dan tidak boleh dipaparkan semula.';
            vault_audit(vault_pdo(), 'SERVER_AGENT_TOKEN_RESET', $deviceId, (string)($newDevice['name'] ?? $deviceId));
        } elseif ($action === 'toggle') {
            $enabled = !empty($_POST['enabled']) ? 1 : 0;
            $stmt = $pdo->prepare('UPDATE server_metric_agents SET enabled=? WHERE device_id=?');
            $stmt->execute([$enabled, $deviceId]);
            $message = $enabled ? 'Agent diaktifkan.' : 'Agent dinyahaktifkan.';
            vault_audit(vault_pdo(), $enabled ? 'SERVER_AGENT_ENABLED' : 'SERVER_AGENT_DISABLED', $deviceId, (string)($devices[$deviceId]['name'] ?? $deviceId));
        }
        vault_touch();
    } catch (Throwable $e) {
        $error = $e->getMessage();
    }
}

$agents = [];
if ($error === '') {
    foreach ($pdo->query('SELECT device_id, enabled, last_seen_at, last_ip, created_at, updated_at FROM server_metric_agents') as $row) {
        $agents[(string)$row['device_id']] = $row;
    }
}
$csrf = vault_csrf_token();
$unlocked = vault_is_unlocked();
$pushUrl = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' ? 'https' : 'http') . '://' . ($_SERVER['HTTP_HOST'] ?? 'www.kmp.matrik.edu.my') . '/zurie/api/server_metrics_push.php';
function sh($v){ return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
?>
<!DOCTYPE html>
<html lang="ms">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="robots" content="noindex,nofollow,noarchive">
<title>Server Agent Setup | Personal NOC</title>
<link rel="stylesheet" href="../assets/css/style.css">
<link rel="stylesheet" href="../assets/css/server-metrics.css">
</head>
<body>
<div class="page-shell server-metrics-shell">
<header class="page-header sm-page-header">
  <div>
    <a href="../index.php" class="back-link">← Dashboard</a>
    <div class="breadcrumb-mini">Monitoring / Server Metrics / Agent Setup</div>
    <h1>🔑 Server Agent Setup</h1>
    <p>Jana token khusus bagi setiap server. Token asal hanya dipaparkan sekali.</p>
  </div>
  <div class="header-actions"><a class="ghost-btn" href="server_metrics.php">📊 Server Metrics</a><a class="ghost-btn" href="credential_vault.php">🔐 Credential Vault</a></div>
</header>

<?php if ($error): ?><div class="sm-notice critical"><?= sh($error) ?></div><?php endif; ?>
<?php if ($message): ?><div class="sm-notice healthy"><?= sh($message) ?></div><?php endif; ?>

<?php if (!$unlocked): ?>
<section class="section-block sm-locked-card">
  <h2>🔒 Credential Vault dikunci</h2>
  <p>Buka Credential Vault dahulu sebelum menjana atau menukar token agent.</p>
  <a class="sm-primary-btn" href="credential_vault.php">Buka Credential Vault</a>
</section>
<?php else: ?>

<?php if ($newToken && $newDevice): ?>
<section class="section-block sm-token-card">
  <div><span class="sm-kicker">TOKEN BAHARU — PAPAR SEKALI</span><h2><?= sh($newDevice['name'] ?? '') ?></h2><p>Device ID: <code><?= sh(array_search($newDevice, $devices, true)) ?></code></p></div>
  <div class="sm-token-value"><code id="generatedToken"><?= sh($newToken) ?></code><button type="button" onclick="navigator.clipboard.writeText(document.getElementById('generatedToken').textContent)">Copy Token</button></div>
  <div class="sm-config-sample">
    <strong>Windows config:</strong>
    <pre>{
  "device_id": "<?= sh((string)array_search($newDevice, $devices, true)) ?>",
  "token": "<?= sh($newToken) ?>",
  "push_url": "<?= sh($pushUrl) ?>",
  "services": ["Apache2.4", "MySQL"]
}</pre>
    <strong>FreeBSD INI:</strong>
    <pre>device_id="<?= sh((string)array_search($newDevice, $devices, true)) ?>"
token="<?= sh($newToken) ?>"
push_url="<?= sh($pushUrl) ?>"
services="apache24,mysql-server"</pre>
  </div>
</section>
<?php endif; ?>

<section class="section-block">
  <div class="section-title row-title"><div><h3>Server Agents</h3><p>Generate/Reset Token akan membatalkan token lama.</p></div></div>
  <div class="sm-agent-grid">
  <?php foreach ($devices as $id => $d): $a = $agents[$id] ?? null; ?>
    <article class="sm-agent-card">
      <div><span class="sm-type">SERVER</span><h3><?= sh($d['name'] ?? $id) ?></h3><p><code><?= sh($d['ip'] ?? '') ?></code> · <?= sh($d['model'] ?? '-') ?></p></div>
      <div class="sm-agent-status">
        <span class="<?= $a && (int)$a['enabled'] ? 'healthy' : 'neutral' ?>"><?= $a ? ((int)$a['enabled'] ? 'Enabled' : 'Disabled') : 'Belum ada token' ?></span>
        <small>Last seen: <?= sh($a['last_seen_at'] ?? 'Belum pernah') ?></small>
      </div>
      <form method="post" onsubmit="return confirm('Generate token baharu untuk server ini? Token lama akan terbatal.');">
        <input type="hidden" name="csrf" value="<?= sh($csrf) ?>">
        <input type="hidden" name="action" value="generate">
        <input type="hidden" name="device_id" value="<?= sh($id) ?>">
        <button class="sm-primary-btn" type="submit"><?= $a ? 'Reset Token' : 'Generate Token' ?></button>
      </form>
      <?php if ($a): ?>
      <form method="post">
        <input type="hidden" name="csrf" value="<?= sh($csrf) ?>">
        <input type="hidden" name="action" value="toggle">
        <input type="hidden" name="device_id" value="<?= sh($id) ?>">
        <label class="sm-toggle"><input type="checkbox" name="enabled" value="1" <?= (int)$a['enabled'] ? 'checked' : '' ?> onchange="this.form.submit()"><span></span> Agent aktif</label>
      </form>
      <?php endif; ?>
    </article>
  <?php endforeach; ?>
  </div>
</section>

<section class="section-block sm-install-card">
  <h3>Fail Ejen</h3>
  <p>Salin folder ejen ke server sasaran. Jangan letak fail config/token dalam folder web.</p>
  <div class="sm-install-links"><a href="../agents/windows/server_metrics_agent.ps1" download>Windows PowerShell Agent</a><a href="../agents/windows/install_task.ps1" download>Windows Task Installer</a><a href="../agents/freebsd/server_metrics_agent.php" download>FreeBSD PHP Agent</a></div>
</section>
<?php endif; ?>
</div>
</body>
</html>
